# Generated by Django 4.1.5 on 2023-02-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praksaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartmentperson',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('appartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='praksaApp.appartment')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='praksaApp.person')),
                ('tenantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='praksaApp.person')),
            ],
            options={
                'db_table': 'Request',
            },
        ),
    ]
