# Generated by Django 4.1.5 on 2023-02-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praksaApp', '0002_alter_building_representativeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='isAactive',
            new_name='isActive',
        ),
        migrations.AlterField(
            model_name='person',
            name='companyId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='praksaApp.company'),
        ),
    ]
