# Generated by Django 4.1.5 on 2023-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praksaApp', '0002_appartmentperson_isowner_useraccount_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='deviceID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
