# Generated by Django 4.1.5 on 2023-02-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praksaApp', '0003_rename_isaactive_useraccount_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='closedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closedBy', to='praksaApp.person'),
        ),
        migrations.AlterField(
            model_name='report',
            name='timeFinished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
