# Generated by Django 4.1.5 on 2023-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praksaApp', '0004_alter_report_closedby_alter_report_timefinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
