# Generated by Django 4.1.5 on 2023-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praksaApp', '0005_report_deleted_report_deleted_by_cascade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='appartmentperson',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='building',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='company',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='country',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='county',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='person',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='report',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='reportstatus',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='role',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='roleperson',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='isActive',
        ),
        migrations.AddField(
            model_name='appartment',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='appartment',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='appartmentperson',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='appartmentperson',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='building',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='company',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='country',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='county',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='reportstatus',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reportstatus',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='role',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='roleperson',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='roleperson',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
